name = "EllipticModule"
uuid = "c86db11a-9a2f-47a1-becb-afa0090b349c"
authors = ["ceciliasecchi <cecilia.secchi98@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
